name: Benrimon
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.931189363123849
title: 'This is a website about me, Leon Benrimon.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: '  '
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fec200'
    - '#d7758e'
    - '#00a390'
    - '#383c9d'
  brandStrength: 0.5625
  lightness: 0.4282121015712619
  saturation: 0.2603846462443471
  rhythmicContrast: 0.3014314949978143
purpose: []
